name: flutter_base_riverpod
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

  cupertino_icons: ^1.0.2
  riverpod: ^2.4.0
  flutter_riverpod: ^2.4.0
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.0.0
  auto_route: 7.7.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  hive_flutter: ^1.1.0
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  freezed: ^2.3.5
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  slang_flutter: ^3.23.0
  slang: ^3.23.0
  shimmer: ^3.0.0
  cloud_firestore: ^4.9.2
  firebase_ui_firestore: ^1.5.11
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.6
  auto_route_generator: 7.2.0
  json_serializable: ^6.7.1
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_gen:
  output: lib/gen
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
 
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
